# config.yaml

# Database settings
database:
  name: "sensor_data.db"
  table: "Experimental_Data_Capture"

# Server settings
server:
  host: "0.0.0.0"
  port: 5000

# Logging settings
logging:
  level: "DEBUG"

# Monitoring settings
monitoring:
  check_interval: 60  # in seconds
  alert_interval: 5   # in minutes
